version: 0.1
phases:
  install:
    commands:
      # Install nodejs https://nodejs.org/en/download/package-manager/
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - apt-get install -y python-software-properties
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:rwky/graphicsmagick
      - apt-get update
      - apt-get install -y graphicsmagick
  pre_build:
    commands:
      - npm install --production
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete build/ "s3://${BUCKET_NAME}"
