version: 0.1
phases:
  install:
    commands:
      # Install nodejs https://nodejs.org/en/download/package-manager/
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - sudo apt-get install python-software-properties
      - sudo apt-get install software-properties-common
      - sudo add-apt-repository ppa:rwky/graphicsmagick
      - sudo apt-get update
      - sudo apt-get install graphicsmagick
  pre_build:
    commands:
      - npm install --production
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete build/ "s3://${BUCKET_NAME}"
